# Generated by Django 6.0.2 on 2026-02-12 22:46

import django.core.validators
import django.db.models.deletion
import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('secret', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('health_rules', models.JSONField(default=telemetry.models.default_health_rules)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField()),
                ('error_count', models.PositiveIntegerField()),
                ('avg_latency_ms', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('p95_latency_ms', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cpu_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('memory_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('uptime_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='telemetry.appclient')),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'captured_at'], name='telemetry_h_app_id_38b755_idx'), models.Index(fields=['captured_at'], name='telemetry_h_capture_6c23c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('app', 'event_id'), name='unique_event_per_app')],
            },
        ),
    ]
